---
openapi: 3.0.2
info:
  title: 'Todo List OpenID Connect '
  version: 1.0.0
  description: Todo List Spec using OpenID Connect
paths:
  /items:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
              examples:
                items:
                  value:
                    - id: "123123"
                      name: Buy Bananas
                      description: Buy Bananas
                    - id: "345345"
                      name: Buy Chocolate
                      description: 85% chocolate
          description: valid response
      operationId: getItems
    post:
      requestBody:
        description: post method
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
            examples:
              item:
                value: |2
                       {
                           "id": "123123",
                           "name": "Buy Bananas",
                           "description": "Buy Bananas"
                       }
        required: true
      responses:
        "201":
          description: Created description
components:
  schemas:
    Item:
      title: Root Type for Item
      description: Item type
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
      example:
        id: "3423432432"
        name: Bananas
        description: Buy bananas at Carrefour
  securitySchemes:
    open-id-connect:
      flows:
        clientCredentials:
          tokenUrl: http://sso-rh-sso.apps.cluster-rkksh.rkksh.sandbox1063.opentlc.com/auth/realms/user8/protocol/openid-connect/token
          scopes:
            openid: ""
      type: oauth2
      description: spec for open-id-connect
security:
  - open-id-connect:
      - openid