---
openapi: 3.0.2
info:
  title: Items List
  version: 1.0.0
  description: 'Items List Spec '
paths:
  /items:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
              examples:
                items:
                  value:
                    - id: "123123"
                      name: Buy Bananas
                      description: Buy Bananas
                    - id: "345345"
                      name: Buy Chocolate
                      description: 85% chocolate
          description: valid Response
      operationId: getItems
    post:
      requestBody:
        description: post method
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
            examples:
              item:
                value: |2
                       {
                           "id": "123123",
                           "name": "Buy Bananas",
                           "description": "Buy Bananas"
                       }
        required: true
      responses:
        "201":
          description: Created description
components:
  schemas:
    Item:
      title: Root Type for Item
      description: Item type
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
      example:
        id: "3423432432"
        name: Bananas
        description: Buy bananas at Carrefour
  securitySchemes:
    open-id-connect:
      openIdConnectUrl: https://user5-admin.apps.cluster-rkksh.rkksh.sandbox1063.opentlc.com/
      type: openIdConnect
      description: Use a 3scale Open Id Connect
